Feature/cart extra features
flutterindiadev/flutter_ecommerce_architecture pull request #6
Opened 2024-02-21 11:07 UTC by namya-jha-17

cart voucher add /remove
order list
order repeat
order cancel

2024-02-22 06:51 UTC, naikdp7 commented on core/data/lib/src/repository/cart_repository_impl.dart
> +    return await networkPort.checkoutCart(checkoutRequest: checkoutRequest);
avoid unnecessary await

2024-02-22 06:51 UTC, naikdp7 commented on core/data/lib/src/repository/cart_repository_impl.dart
> +    throw UnimplementedError();
why its not implemented ?

2024-02-22 06:52 UTC, naikdp7 commented on core/domain/lib/src/usecase/cart/cart_address_change_usecase.dart
> +    return right(true);
validations?

2024-02-22 06:52 UTC, naikdp7 commented on core/domain/lib/src/usecase/cart/cart_voucher_add_usecase.dart
> +    if (Validator.isCartAvailable(this.isVoucherIdAvailable)) {
why we are sending voucherId in this function?

2024-02-22 06:53 UTC, naikdp7 commented on core/domain/lib/src/usecase/cart/cart_voucher_add_usecase.dart
> +          error: ErrorInfo(message: "voucher is used already"),
dont provide message from here

2024-02-22 06:53 UTC, naikdp7 commented on core/domain/lib/src/usecase/cart/cart_voucher_add_usecase.dart
> +          type: ErrorType.uiEmptyEmail,
error type is wrong

2024-02-22 06:53 UTC, naikdp7 commented on core/domain/lib/src/usecase/orderlist/order_rating_usecase.dart
> +    return Right(true);
validations?

2024-02-22 06:53 UTC, naikdp7 commented on core/domain/lib/src/usecase/orderlist/order_repeat_usecase.dart
> +    return Right(true);
validations?

2024-02-22 06:54 UTC, naikdp7 commented on infrastructure/network-retrofit/lib/src/models/Order_Repeat/order_repeat_response_entity.dart
> +   OrderRepeatEntity(status: data.status));
please explain this

2024-02-22 06:54 UTC, naikdp7 requested changes
Requested changes

2024-02-22 07:37 UTC, namya-jha-17 commented on core/data/lib/src/repository/cart_repository_impl.dart
> +    return await networkPort.checkoutCart(checkoutRequest: checkoutRequest);
ok

2024-02-22 07:44 UTC, namya-jha-17 commented on core/domain/lib/src/usecase/cart/cart_voucher_add_usecase.dart
> +    if (Validator.isCartAvailable(this.isVoucherIdAvailable)) {
it was typo

2024-02-22 07:44 UTC, namya-jha-17 commented on core/domain/lib/src/usecase/cart/cart_voucher_add_usecase.dart
> +          type: ErrorType.uiEmptyEmail,
resolved

2024-02-22 08:14 UTC, namya-jha-17 commented on core/domain/lib/src/usecase/cart/cart_address_change_usecase.dart
> +    return right(true);
done

2024-02-22 08:14 UTC, namya-jha-17 commented on core/domain/lib/src/usecase/cart/cart_address_change_usecase.dart
> +    return right(true);
done

2024-02-23 11:32 UTC, naikdp7 approved these changes

2024-02-23 11:32 UTC, merged